# Data sources

Siqi Chen was responsible for collecting the data and the video games sales dataset studied in this project was collected from Kaggle.com\
link: https://www.kaggle.com/ashaheedq/video-games-sales-2019.
\

The data set we used is a continue work on this original dataset\
link：https://www.kaggle.com/gregorut/videogamesales
\
\
There are total 55,792 records in the dataset as of April 12th, 2019. It was generated by a scrape of vgchartz.com.\

The publisher collected over 55,000 records from VGChartz, which is a video game sales tracking website that provides weekly sales figures of console software and hardware by region. VGChartz provides sales data for all current gaming consoles and portables, as well as retail gaming software for all major platforms. The main service provided by VG Chartz is weekly charts of hardware and software sales for the video game consoles sold by Nintendo, Sony, and Microsoft.\

This dataset is credible since i) it includes metadata, such as subtitle, tags, overview description and cover image, ii) it has file descriptions and used appropriate file formats, and iii) it has a public kernel and task. Combined, it achieved a total usability score of 7.6. We chose this dataset over the original one because it was a latest version and had higher usability score (only 5.9 was reached for the original dataset, and the file description was missing as well).\
\
Variables included but not limitied in this study are: 

- Rank - Ranking of overall sales\
- Name - Name of the game\
- Platform - Platform of the game (i.e. PC, PS4, XOne, etc.)\
- Genre - Genre of the game\
- ESRB Rating - ESRB Rating of the game\
- Publisher - Publisher of the game\
- Developer - Developer of the game\
- Critic Score - Critic score of the game from 10\
- User Score - Users score the game from 10\
- Total Shipped - Total shipped copies of the game\
- Global_Sales - Total worldwide sales (in millions)\
- NA_Sales - Sales in North America (in millions)\
- PAL_Sales - Sales in Europe (in millions)\
- JP_Sales - Sales in Japan (in millions)\
- Other_Sales - Sales in the rest of the world (in millions)\
- Year - Year of release of the game\
\

It is a pity for us to see its lateset updates was two years ago. We were not able to analyze the new released PS5 sales figures since the gaming cosole was released in November 2020 and the data has not been collected. \

After carefully inspecting the dataset, we found many data in our cvs data file were missing. For instance, column "VGChartz_Score" did not contain any value. A lot of sales data, including Global sales, NA sales, PAL sales, JP sales and other sales were not available either. We will first remove those NA values and check if the data is still usable for later study. 
